### ISSUE TITLE
Just wondering...

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_builder#2]
Do you have a .gitignore within a .gitignore?

https://github.com/kendraio/kendra_builder/blob/master/htdocs/.gitignore

**Comment by iAugur** [comment]
They work at what ever level - typically you have it in the root - but subfolders can have their own - so if you only wanted to gitignore certain files in certain folders etc
But in our case they are additive and don't fight
you can negate rules from the root in a subfolder - but who does that...

**Comment by dahacouk** [comment]
Coolio!
